# Generated by Django 6.0.3 on 2026-07-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_survey_questions_per_page_survey_is_active_survey_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created_at'], 'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
    ]
